// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_FBPROTOCOL_FBPROTOCOL_H_
#define FLATBUFFERS_GENERATED_FBPROTOCOL_FBPROTOCOL_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 24 &&
              FLATBUFFERS_VERSION_MINOR == 3 &&
              FLATBUFFERS_VERSION_REVISION == 7,
             "Non-compatible flatbuffers version included");

#include "Enum_generated.h"
#include "FBP_Bullet_generated.h"
#include "FBP_Chat_generated.h"
#include "FBP_Enemy_generated.h"
#include "FBP_Enter_generated.h"
#include "FBP_Item_generated.h"
#include "FBP_LogIn_generated.h"
#include "FBP_NetworkLatency_generated.h"
#include "FBP_Phero_generated.h"
#include "FBP_Player_generated.h"
#include "Struct_generated.h"
#include "Transform_generated.h"

#endif  // FLATBUFFERS_GENERATED_FBPROTOCOL_FBPROTOCOL_H_
